In [1]:
import numpy as np
import pandas as pd

# QUESTION 1

In [4]:
np.__version__ # version of numpy

'1.21.5'

In [9]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

'wget' is not recognized as an internal or external command,
operable program or batch file.


In [10]:
df = pd.read_csv('hw-1.csv')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [13]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

# QUESTION 2

In [27]:
df["Make"].describe()

count         11914
unique           48
top       Chevrolet
freq           1123
Name: Make, dtype: object

There are 11914 records in the dataset

# QUESTION 3

In [71]:
df["Make"].value_counts().head(3) # most frequent car manufacturers (top-3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

Chevrolet, Ford, Volkswagen are the top 3

# QUESTION 4

In [45]:
df[df.Make == "Audi"].Model.describe() # number of unique Audi car models

count     328
unique     34
top        A3
freq       47
Name: Model, dtype: object

There are 34 unique Audi columns

# QUESTION 5

In [50]:
df.isnull().sum() #  columns in the dataset have missing values

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

5 columns in the dataset has missing values

# QUESTION 6

In [57]:
#Find the median value of "Engine Cylinders" column in the dataset.
df["Engine Cylinders"].median()

6.0

In [62]:
#calculate the most frequent value of the same "Engine Cylinders"
most_freq_cyl = df["Engine Cylinders"].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

4.0 is the most frequent value

In [63]:
# Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
# And recalculate median
df["Engine Cylinders"].fillna(4.0).median()

6.0

Median remains unchanged

# QUESTION 7

In [64]:
df_Lotus = df[df.Make == "Lotus"] # Select all the "Lotus" cars from the dataset
df_Lotus = df_Lotus[["Engine HP", "Engine Cylinders"]] # Select only columns "Engine HP", "Engine Cylinders".
df_Lotus = df_Lotus.drop_duplicates() # drop all duplicated rows

In [66]:
df_Lotus.shape # you should get a dataframe with 9 rows

(9, 2)

In [70]:
X = df_Lotus.values # Get the underlying NumPy array of df_Lotus
XTX = X.T.dot(X) # Compute matrix-matrix multiplication between the transpose of X and X

XTX_inv = np.linalg.inv(XTX) # Compute the inverse of XTX
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800] # Create an array y
w = XTX_inv.dot(X.T).dot(y) # Multiply the inverse of XTX with the transpose of X, and then multiply the result by y
w

array([  4.59494481, -63.56432501])

Value of the first element of w is 4.59494